language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2.300
os:
#  - linux CircleCI does linux tests
  - osx

install:
  - dotnet restore

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script:
  - dotnet build -c Release --no-restore --framework netstandard2 ./src
  - dotnet test --logger "console;verbosity=normal" -c Release --no-restore --framework netcoreapp2.2 ./test --filter TestCategory!=IPv6
