# gitversion will change the version number
version: x-{build}

for:
-
  branches:
    only:
      - master

  environment:
    git_token:
      secure: NeX5NCOUXsCLc1UjTJjqB9F02FZ8Wq0VsxqTXC8kBdyK6zjxjebrf/9Da2sY1Kql

configuration: Release
os: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:git_token):x-oauth-basic@github.com`n"
  - git config --global user.email "noreply@emanon.org"
  - git config --global user.name "Appveyor CI"

cache:
  - '%APPDATA%\npm-cache'               # npm cache
  - '%USERPROFILE%\.nuget\packages'     # nuget cache

environment:
  COVERALLS_REPO_TOKEN:
    secure: 2/rbxuse7F3p04C3Lin9tH/fCwigpYAW2bB+4hv8nyCcHo+VMjbTCM2Tf/f4TXIQ
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

# tools we need for bulding/testing/deploying
install:
  - choco install gitversion.portable -y

# gitversion will change the assembly info
pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: gitversion /output buildserver /updateAssemblyInfo >gitversion.log

build_script:
  - dotnet build -c %CONFIGURATION% -p:Version=%GitVersion_MajorMinorPatch% -p:AssemblyVersion=%GitVersion_MajorMinorPatch%

test_script:
  - dotnet test --logger "console;verbosity=normal" -c %CONFIGURATION% --no-build --no-restore test

after_test: 
# Generate coverage report
    - dotnet test -c %CONFIGURATION% -f netcoreapp2.2 --no-build --no-restore test /p:CollectCoverage=true
    - choco install codecov -y
    - codecov -f "test/coverage.opencover.xml"
    - dotnet tool install --global coveralls.net --version 1.0.0
    - if defined COVERALLS_REPO_TOKEN 
        csmacnz.coveralls.exe 
        --opencover -i test/coverage.opencover.xml --useRelativePaths --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%

# Build documentation in doc\_site
# v2.43 is requiring VS 2019!!!
    - choco install docfx -y --version 2.42 --force
    - docfx doc\docfx.json --logLevel Warning --warningsAsErrors
    - 7z a -tzip docs.zip doc\_site
    - appveyor PushArtifact docs.zip
    - if defined git_token npm install gh-pages@2.0 -g
    - if defined git_token gh-pages -d doc\_site -m "new docs %GitVersion_FullSemVer%"

artifacts:
  - path: 'src/**/*.nupkg'
    name: nupkg
  - path: 'src/**/*.snupkg'
    name: snupkg

# publish NuGet package on tag build
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
deploy:
- provider: NuGet
  api_key:
    secure: OdmGEj/l0K0ZPDmXAYx+fryCzV012eTrM29ALBuL0waxvwLvrufdDXiI+1iNhWEG
  on:
    appveyor_repo_tag: true
